### ISSUE TITLE
Linux support for desktop version

### ISSUE THREAD

**Issue by blargle-ragequit** [awhipp/evetrade#107]
So far Linux users are required to use the evetrade.space website because when run in WINE the desktop application opens as only a blank window.  I'm not asking for a native Linux version, just at least troubleshooting the Windows application in WINE to figure out how to get it to run in that compatibility layer correctly.

**Comment by awhipp** [comment]
@blargle-ragequit 

Simple enough request. I just used the node package Nativefier.

I'll go through and create a release which supports Windows, Mac, and Linux (Ill test against my Ubuntu machine). When its ready, I'll send you the link and ask you to test as well. Thanks!

**Comment by awhipp** [comment]
@blargle-ragequit All set. Tested PR #109 on dev.evetrade.space

Merging into master now so it should be live for download on evetrade.space in the next few minutes.

**Comment by awhipp** [comment]
![Capture](https://user-images.githubusercontent.com/6343174/59211752-a6145000-8b7e-11e9-9828-c77082024776.PNG)
