### ISSUE TITLE
Minimum ROI setting appears to be ignored

### ISSUE THREAD

**Issue by timegrinder** [awhipp/evetrade#118]
**Describe the bug**
Return on Investment (ROI) minimum setting appears to be ignored.

**To Reproduce**
Any search option appears to ignore the ROI setting (whether it's default, set, set with minimum profit, or on its own etc)

**Expected behavior**
The table should be filtering any ROI numbers that fall below the specified (or default if unspecified) setting but is showing all ROI's regardless.

**Screenshots**
![evetrade spaceROIissue](https://user-images.githubusercontent.com/12099413/69497680-b69f6380-0f2f-11ea-8d79-3026b018eef0.jpg)

**Desktop (please complete the following information):**
 - Browser:  Chromium: 78.0.3904.97

**Additional context**
Line 421+423 of region.js is where the check is done in this example, though it occurs on both region and station to station search types.

**Comment by awhipp** [comment]
@timegrinder Fixed in the latest dev commit. Currently in testing at dev.evetrade.space

@psolyca Caught a bug with #120 where security and safety were strings and converted to NaN

See the fix here: https://github.com/awhipp/evetrade/commit/03009d3204e069d621b5d0b80a7b688fb2fd6d75

**Comment by psolyca** [comment]
Please reopen.
I change the value on setDefaultVal but sometimes, real strings are passed to the function (security status) so NaN is returned.
So I have to modify my fix.

**Comment by psolyca** [comment]
Hahaha I propose a PR but did not see this fix on my smartphone ^^;
