### ISSUE TITLE
Latest dev versions tax handling

### ISSUE THREAD

**Issue by timegrinder** [awhipp/evetrade#122]
**Describe the issue**
Tax settings on the latest dev version appear to be set to int and not float (ie, putting in a tax amount of '2.8%' truncates the .8 and calculates tax rates based on 2%.

**Expected behavior**
The 'tax' entry should be float (if it's not, or otherwise handle decimals) and it may be better to change it to a fixed drop down containing only the possible tax amounts instead of letting a user input a number (as it's only possible to have 5, 4.45, 3.9, 3.35, 2.8, 2.25) and users make errors :)

Thanks for the good work to those involved by the way, the updates are nice and solving many problems.

**Comment by psolyca** [comment]
I was thinking of that but If you have an event like the BlackFriday when taxes were 2.5% you are stuck.

But you are right, we convert values to int not float.

**Comment by timegrinder** [comment]
For events there could be an option for 'other' and then allow custom input, or at least provide the presets built in but leave it still permit people to type in, so they can use the presets for convenience.

**Comment by psolyca** [comment]
@timegrinder could you try this [Preview #125](https://deploy-preview-125--evetrade.netlify.com/) ?

**Comment by timegrinder** [comment]
@psolyca At first testing it appears to work for the preset tax amounts (and the numbers appear to come out correctly compared to my own calculations), however the 'Other' option seems to be passed directly as a string, filtering by 'Other%' and filtering out all results.

If you want to see the results and test for yourself just compare any preset % against the same number in the 'Other' field.

Other than that, the Tax choice interface looks really good, thank you!

**Comment by psolyca** [comment]
@timegrinder Oops I forgot to change the calculation ^^;

Should be fine now.
Please retest the same link.

**Comment by timegrinder** [comment]
@psolyca Looks good, seems to work exactly how I imagined it, thank you very much!

**Comment by awhipp** [comment]
@timegrinder @psolyca 

Code looks good, and you both seem to have tested so I merged it into dev.
