### ISSUE TITLE
Button to clear stations

### ISSUE THREAD

**Issue by psolyca** [awhipp/evetrade#143]
**Is your feature request related to a problem? Please describe.**
When using the "Add system" feature on station haul, there is no simple way of resetting the value.
One have to click on each station to delete them.

**Describe the solution you'd like**
Adding a reset button on each input (start and end) could be better than reloading the page or clicking each line.

**Comment by psolyca** [comment]
Here we go.
What do you think of it ?

![Reset_button](https://user-images.githubusercontent.com/3757683/73611073-69e6a180-45de-11ea-90df-da98cb510d51.png)

Same for end station.
The button appear when 5 stations are selected.
It is lower than other buttons due to floating box but it is not shocking.

**Comment by awhipp** [comment]
Looks good to me!
