### ISSUE TITLE
Trading with stations around the start station

### ISSUE THREAD

**Issue by psolyca** [awhipp/evetrade#144]
**Is your feature request related to a problem? Please describe.**
Currently, we can choose to trade from one station to another or to a complete system (or more).
But could it be possible (is there an advantage) to trade with all stations in the vicinity of a station ?
With a station in the same constellation as the start station, in the same region, @ 1 or X jumps (max ?)

**Describe the solution you'd like**
Having a button / drop-down menu to choose directly without having to look in Dotlan all stations in the constellation / region / @ 1 to X jumps (max to define)

**Comment by awhipp** [comment]
It would have a benefit but complexity is a concern. It would require a number of API calls per station to determine order and distance from each station. Pretty similar to the traveling salesman problem because for every station of interest we would need to determine the number jumps away that each station is to determine if an order can be executed. Station to station this would not be a problem but if we included regions then it gets exponentially more challenging.

**Comment by psolyca** [comment]
Ok, I reread what I have written and I understand what you mean but it is not what I want ^^
Currently, to have a list of end stations, you have to select them one by one or use the "Shift" key to select all station in the system of end station.
What I want is to add in the list of end stations, all stations in the constellation, the region or at X jump from the start station.
Then it is the same algorithm from station to station.

**Comment by awhipp** [comment]
Ah I see. That does make it simpler .

**Comment by psolyca** [comment]
Same principle as #145 .
Automatically fill end stations nearby start station in constellation (for the time being)

Only one start station can be used otherwise a message is displayed.
This, to avoid to many requests.

With a drop-down menu
![Constellation_dropdown](https://user-images.githubusercontent.com/3757683/73600322-cf8b4d00-454e-11ea-9e11-47f5418aa8ac.png)


With a button
![Constellation_button](https://user-images.githubusercontent.com/3757683/73600325-d87c1e80-454e-11ea-8f38-c9dba4596b8e.png)

With a checkbox
![Constellation_checkbox_unticked](https://user-images.githubusercontent.com/3757683/73600344-2729b880-454f-11ea-8242-fe37d2f7055e.png)

![Constellation_checkbox_ticked_noerror](https://user-images.githubusercontent.com/3757683/73600347-30b32080-454f-11ea-8a26-ff6a43373bac.png)

![Constellation_checkbox_ticked_error](https://user-images.githubusercontent.com/3757683/73600348-3872c500-454f-11ea-8a51-a131cf6815f2.png)

After choosing the way to get it, I will expand the same to region and to X jumps (max not defined yet).

**Comment by psolyca** [comment]
Can not do it for all stations in the region of start station... too many requests to ESI server (not enough resources for the server).

**Comment by psolyca** [comment]
I am thinking of a way to cache the first request to avoid too many resquests to the ESI server as all requests are the same.

**Comment by psolyca** [comment]
I need to rethink on the subject... cause :

- station to region search is like region to region with a search on a station name.
- Station to constellation retrieve too few trades (so not really usable).
- Station to stations at X jumps (too many requests, I have to see how to manage and if it is really helpfull).
