### ISSUE TITLE
Trading with regions around the start region

### ISSUE THREAD

**Issue by psolyca** [awhipp/evetrade#145]
**Is your feature request related to a problem? Please describe.**
Currently, we can trade from one region to another one. I could be great to have a button to choose all regions around the start region.

**Describe the solution you'd like**
Having a button / drop-down menu to choose all regions around.

**Additional context**
Is the number of requested to the Eve server too important ?

**Comment by awhipp** [comment]
EVE ESI does not have a rate limit but if they see you are abusing the number of requests per minute/second they will lock your IP from submitting requests for a period of time. If this was implemented we would need to implement a rate limiter on our end that keeps the requests within a reasonable frequency.

**Comment by psolyca** [comment]
@awhipp 
Do you prefer ?

- With a button
![R2R_all-arround_button](https://user-images.githubusercontent.com/3757683/72726117-da75d300-3b87-11ea-8e1b-f85b263beab7.png)

- With a drop-down (I could add a separator! Maybe! Really do not know!)
![R2R_all-arround_dropdown](https://user-images.githubusercontent.com/3757683/72726128-e2357780-3b87-11ea-8bf2-cbdfa4099378.png)

**Comment by awhipp** [comment]
I like option one, but what if we had it as a checkbox as well. So it would read "Include nearby regions as well"

**Comment by psolyca** [comment]
![R2R_all-arround_checkbox](https://user-images.githubusercontent.com/3757683/72818159-467d3780-3c6b-11ea-8c47-41176ec95627.png)

I am not really enjoyed by this idea :p
To confusing, people can think :

> Do we select a "Destination Region" and when checked, all regions nearby the destination region are taken as well ?

Could the checkbox be under "Starting Region" ?
When checked, "Destination Region" could disappeared?

![R2R_all-arround_checkbox2_untick](https://user-images.githubusercontent.com/3757683/72818893-88f34400-3c6c-11ea-9487-165e116fb1f1.png)

![R2R_all-arround_checkbox2_tick](https://user-images.githubusercontent.com/3757683/72818901-8b559e00-3c6c-11ea-9bc4-2578c08b327a.png)

**Comment by awhipp** [comment]
Ahhhh I see. I misunderstood the feature. This looks good to me. Maybe "Sell to nearby regions"?

I thought it was starting at the region and near by regions and selling to the region and the nearby regions. This makes more sense.

**Comment by psolyca** [comment]
This way, is it mush better ?

![R2R_all-arround_checkbox3_untick](https://user-images.githubusercontent.com/3757683/73058522-1cf32480-3e94-11ea-8c91-e840e2579799.png)

![R2R_all-arround_checkbox3_tick](https://user-images.githubusercontent.com/3757683/73058713-78251700-3e94-11ea-88c5-933ab03c58ca.png)

**Comment by psolyca** [comment]
Was testing yesterday the checkbox version.
@awhipp which one do you prefer ?
I need to know before debugging the version ^^
One little think bothered me is the percentage which do not take into account everything (only the first route).

**Comment by awhipp** [comment]
I do like the second one more. Makes more sense (at least to me). Buying from first region and selling to all surrounding regions (as the destination).

Would it be a challenge to center that checkbox under "Destination Region"? Just a small UI tweak to keep it symmetrical.

**Comment by psolyca** [comment]
Done in #157.
