### ISSUE TITLE
Adding stations directly to Eve route

### ISSUE THREAD

**Issue by psolyca** [awhipp/evetrade#147]
**Is your feature request related to a problem? Please describe.**
Being able to add the route directly to Eve from Eve Trade.

**Describe the solution you'd like**
Like Evemarketer or other websites, right click or a button to add the choosen station(s) in Eve pathway (Set destination / Add waypoint).

**Comment by psolyca** [comment]
I have implemented the connection to Eve on my working dir and get character informations and display them on the main page as well as taxes (Account Level).
BTW a PHP script needs to be used to hide API secret key and do the backend of login and requesting data to Eve which can not be done with Netlify. Thus, an other server must be used.
No solution could be done with JS.

**Comment by awhipp** [comment]
Correct assumption. Unfortunately that is the problem I've had with the authed endpoints. I need to set things up with a backend and decouple the frontend which I do not have the time/resources to do.
