### ISSUE TITLE
Include citadels

### ISSUE THREAD

**Issue by psolyca** [awhipp/evetrade#148]
**Describe the bug**
Not really a bug but a source DB "failure"!
Do we need to include citadels as the DB from https://stop.hammerti.me.uk has not been updated since 25/09/2018 (https://stop.hammerti.me.uk/citadelhunt/structures) ?

**Additional context**
I do not know any other up to date DB for citadels.

**Other possibility**
With a login capability citadels accessible to the character could be fetched through ESI API.
Following #147 ^^

**Comment by awhipp** [comment]
I agree that it would be good to update how we get that information but unfortunately I am unsure how we would provide an authed capability without a ground up refractor. Likely not something we could do without a backend component (built in something like node). 

I'll take the action to investigate other means for getting citadel information. Largely the hammerti.me.uk API is just used to get the citadel information. 

The actual trades are available without needing auth.

**Comment by psolyca** [comment]
I already built something for auth not in Node but in PHP (will see for Node).
BTW, both need a server (independant or not) to run.
I will try to provide a test server for you but I have to rebase the work on the last dev.

For all other information, no need to auth.

**Comment by awhipp** [comment]
Unfortunately I get a 502 when I attempt to login.
Depending on traffic and how the PHP backend works I might be able to use my Google Cloud account to setup the server.

**Comment by psolyca** [comment]
Hooo, my bad.
I have rebooted yesterday and did not launch the PHP runtime ^^
Should be ok and launched at start.
