### ISSUE TITLE
Filter for blueprints/trade goods/ Illegal Goods

### ISSUE THREAD

**Issue by Carinea88** [awhipp/evetrade#162]
Small note: I only do region to region trading.

**Is your feature request related to a problem? Please describe.**
At the moment I get quite big lists of items that include items like: Blueprints, Trade Goods, and Illegal goods.
These items show as decent profits but are most of the time terrible to sell or scams :(

**Describe the solution you'd like**
A simple tick box where one could select to filter trade goods and blueprints would be great.

**Additional context**
And just wanted to say I love this trading program :)

**Comment by psolyca** [comment]
Hello,

Could be done but one need to filter out by Group... So we need to filter not only those ones but all groups.
Added to my ToDo list unless @awhipp wants to take it ^^

**Comment by awhipp** [comment]
@psolyca Sorry I just saw this. I've been pretty busy since march. I've not visited github much since. Feel free to tackle and open PRs as needed. I'll test and merge as I see them come into my inbox.
