### ISSUE TITLE
Results not loading in station to station trading, Stuck at a random percentage between 80% to 99%

### ISSUE THREAD

**Issue by Kikukino** [awhipp/evetrade#165]
**Describe the bug**
At the results page no items show and the percentage bar stays the same no matter how long i wait.
However station trading and region trading do work perfectly.

**To Reproduce**
I have tried different parameters for the roi and only return profits above with no luck

**Screenshots**
https://imgur.com/a/3xUfURI

**Desktop
 - OS: Windows
 - Browser chrome
 - Version 6.5

**Comment by awhipp** [comment]
Sorry I've been busy. Thanks! Putting in a fix for this now.

**Comment by awhipp** [comment]
Deployed and tested fix on dev.evetrade.space

**Comment by awhipp** [comment]
Deploying to evetrade.space. Closing ticket.
