### ISSUE TITLE
Add other structures, not just stations

### ISSUE THREAD

**Issue by tobydjones** [awhipp/evetrade#167]
**Is your feature request related to a problem? Please describe.**
I've just started EVE
My home is: Clellinon VI - Moon 11 - Center for Advanced Studies School
And I often buy things at: Alentene - IChooseYou Market and Industry
I'd like to look at trading between these two places, but IChooseYou is not on the drop down list.
I guess that's because it's not a station, but a different sort of structure

**Describe the solution you'd like**
Add other structures to the start/end point drop down lists as well as stations.

**Comment by awhipp** [comment]
Sorry I've been busy and have neglected this page, but I am aware of the need to add Citadels. It was originally a feature but our API provider is no longer available so we need another service that provides the same content.

In the meantime I have disabled the use-less citadel button.
