### ISSUE TITLE
Love this program, but it doesn't work anymore.  Doesn't seem able to communicate w/ Eve... Just stay stuck at 0% on search.  True for all types of trades.

### ISSUE THREAD

**Issue by Teamshrink** [awhipp/evetrade#172]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by awhipp** [comment]
Hi @Teamshrink, is this still happening? It looks like EVE's APIs might have been down.  I just executed a search and it is returning results.
