### ISSUE TITLE
Add "(net profit)*(X-day volume)" to station-station trading

### ISSUE THREAD

**Issue by Snooober** [awhipp/evetrade#173]
**Is your feature request related to a problem? Please describe.**
I often want to look at the profit relative to the market volume of an item. So if you multiply (net profit)*(volume) it is valuable to compare it to other items. (I prefer using 30-day volume for this calculation). Volume alone is not that valuable to me nor is profit alone.

**Describe the solution you'd like**
An additional column with (net profit)*(X-day volume)

**Describe alternatives you've considered**
Currently I download the excel file and make my own.

**Comment by awhipp** [comment]
Hey @Snooober 

This should be simple enough, but I am wondering what to call the column?
