### ISSUE TITLE
"Sell to nearby regions" option returns the "A starting region, and a destination is required." error

### ISSUE THREAD

**Issue by Merrick919** [awhipp/evetrade#177]
**Describe the bug**
Selecting the `Sell to nearby regions` option returns the `A starting region, and a destination is required.` error if an attempt was made before to search without the option selected and without a `Destination Region`

**To Reproduce**
1. Select `Region to Region`
2. Select a `Starting Region`
3. Without selecting the `Sell to nearby regions` option and without selecting a `Destination Region`, attempt to search
4. Select the `Sell to nearby regions` option and attempt to search

**Expected behavior**
The search will work and there will be no error

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home 21H1 10.0.19043 Build 19043
 - Browser: Microsoft Edge 95.0.1020.44 (Official build) (64-bit)

**Comment by awhipp** [comment]
Good find. Ill add this to the backlog.

**Comment by awhipp** [comment]
This is going to be addressed in the coming month with the overhauled UI and backend. Closing.
