### ISSUE TITLE
Support 8% sales tax (for alpha players)

### ISSUE THREAD

**Issue by BonsaiDen** [awhipp/evetrade#178]
**Is your feature request related to a problem? Please describe.**

Just started the game, really love the tool saves me a lot of trouble search through marketer my own - however the profit numbers are "a bit" (depending on the margin up to 50%) off since I cannot skill accounting at all and so am stuck at 8% sales tax.

**Describe the solution you'd like**

Add 8% sales tax as an option or allow more than 5% when entering a custom sales tax.

**Describe alternatives you've considered**

Spending 15 bucks on omega - but I can also open a PR myself.

**Additional context**
-

**Comment by awhipp** [comment]
Hey @BonsaiDen thanks for this.

I am actually actively working to overhaul and revamp the application to be more performant (ideally 50% or faster queries).

I will add this to the backlog for the updated version, I have not played EVE in a while and I did not realize they increased the default. THanks!

**Comment by awhipp** [comment]
@BonsaiDen This has been tested in dev (dev.evetrade.space) and merged into master. Sales Tax is now 8% (down to 3.6%) and Brokers fees start at 3%
