### ISSUE TITLE
Footer covering search button

### ISSUE THREAD

**Issue by ree17017** [awhipp/evetrade#190]
**Describe the bug**
When doing a Station to Station or Region to Region search the footer covers the search button

**To Reproduce**
1. Go to https://evetrade.space/?trade=s2s or https://evetrade.space/?trade=r2r
2. Try  to click on search

**Expected behavior**
Be able to click on the search button

**Screenshots**
![image](https://user-images.githubusercontent.com/43451476/178800343-a37f9ec5-89cc-41e1-b690-71f36a658b9f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - [Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by awhipp** [comment]
@ree17017 Thanks for bringing this to my attention. Unfortunately, I will not be able to fix this as I am completely overhauling the UI. I am hoping to have the deployment complete by the end of the month which should address this bug. In the meantime, it looks like you are using Brave (which I do not test against), can you try another browser in the meantime?

You can track the progress here: https://feature-7-0-api-overhaul--evetrade.netlify.app/

**Comment by ree17017** [comment]
Thanks, I will wait until the overhaul is done. 

Side note: I tested this in chrome and I see the same issue.

**Comment by awhipp** [comment]
@ree17017 Very interesting. Tried across my 3 computers (different resolutions) and I cannot replicate.

Can you provide me what resolution you are using? I'll see if I can replicate on my machine to ensure it doesn't happen with the overhaul.

**Comment by ree17017** [comment]
Display Resolution: 1920 X 1080
Page Zoom is 100%

You have a postion of absolute on your footer. Change it to `relative` and that fixed it.

**Comment by awhipp** [comment]
@ree17017 good catch. I haven't updated the css in two years. I'll create a hot fix tomorrow and resolve this. I always assumed it was relative based on how the UI looks on my end. It's been a while. Apologies. :)

**Comment by ree17017** [comment]
Tested and looks great! Thank you for fixing this so quickly! ❤️
