### ISSUE TITLE
Proposal: Profit per m³

### ISSUE THREAD

**Issue by re4jh** [awhipp/evetrade#47]
Hey this is a great tool that you created there.
I just wanted to make a proposal.
When I am searching for a trade between two stations it would by great to have a column with the value profit per m³ by that I could sort the results.

**Comment by awhipp** [comment]
Unfortunately I have thought about that, but since the API for ships only returns the unpackaged m3 it actually skews the results. Due to that, and the fact that there are already too many columns for some laptop screens I decided against it. 

Thanks for the proposal.
