### ISSUE TITLE
Proposal: Volume per Item at one station

### ISSUE THREAD

**Issue by re4jh** [awhipp/evetrade#48]
There is another proposal i would like to make to you.
When I am searching for profits at one station the average daily volume all the nice numbers about possible profits are nice to now, but i should be able to compare them with the average traded number per day of this item.

**Comment by awhipp** [comment]
Already added as a ticket #46 -- unfortunately I have had no time to continue support. Feel free to branch the code and add the logic if you find the time. I'll gladly accept the PR.
