### ISSUE TITLE
Populate Suggestion Properly

### ISSUE THREAD

**Issue by awhipp** [awhipp/evetrade#87]
**Is your feature request related to a problem? Please describe.**
When clicking a suggested station/region it does not place it in the correct input

**Describe the solution you'd like**
It should be placed in the typed input section not the shaded one

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by psolyca** [comment]
Why do you want them in the typed input section ?
Or I do not understand the "bug" !

**Comment by awhipp** [comment]
This does not seem to be a bug any longer. Believe I addressed it in a prior PR and never removed the ticket :)
