### ISSUE TITLE
Support Browser History and Bookmarking

### ISSUE THREAD

**Issue by neocryptek** [awhipp/evetrade#94]
**Is your feature request related to a problem? Please describe.**
Searches cannot be saved, bookmarked, etc as the results page does not save the search parameters in the URL. Browser history/back button is also broken since the URL does not change, the browser thinks it is a single page.

**Describe the solution you'd like**
As soon as the user presses search, the search form options should be converted into URL parameters and the browser URL modified. You don't have to do a full page refresh if you want to stay SPA. Then all normal browser features would return: history, back button, ability to bookmark, etc. 

The single page app on first load needs to check if a search already exists in the URL and start a new search with those parameters (so loading the site from a saved bookmark will work and not just load the homepage). Any missing optional parameters in the URL would use the defaults (just like the search form). Any missing required parameters would of course return an error that they are required.

For example:
https://evetrade.space/s2s?start=Hek,Dodixie&end=Rens&buying=sell&selling=buy&profit=500000&roi=4&cargo=150&budget=1000000

URL Path 

- /s2s is trade type (single station, station to station, or region to region)

GET Parameters

- start is starting station (list to support more than one)
- end is ending station (list to support more than one)
- buying/selling is order type to use (sell or buy)
- profit is profit
- roi is roi
- cargo is cargo
- budget is budget
- ETC.

**Describe alternatives you've considered**
Most SPA libraries have a built in way to accomplish this, you should probably use whatever is standard for the framework you are using (both pushing entries onto the history stack and reading existing URLs and routing to appropriate page logic). But the raw HTML5 is here: https://developer.mozilla.org/en-US/docs/Web/API/History

**Additional context**
Users give SPA apps a bad name when they break basic browser functionality like the back button, history, bookmarking, etc. :) 

Thank you for all your hard work making this site, it's been super useful!

**Comment by awhipp** [comment]
Great idea. Thanks for the submission! I actually played around with this a few months ago, I just got caught up in commenting and trying to get things ready. 

Honestly shouldn't be too hard to implement. Just no time for me to implement it currently. 

Ideally it would just pass the query params to the `init()` function on startup.

**Comment by awhipp** [comment]
Complete
