### ISSUE TITLE
selling to cheapest sell orders

### ISSUE THREAD

**Issue by Sukkulente** [awhipp/evetrade#99]
**Station to Station Trading:**

**Is your feature request related to a problem? Please describe.**
Selling to Sell orders is not really helpful. It appears to compare the most expensive target sell with the cheapest source sell order order to calculate returns and this can produce enormouse returns that may never be achieved.

**Describe the solution you'd like**
as in the game one must undercut the cheapest sell order:
buy cheapest sell order in source station --> sell 0,01 ISK below the cheapest sell order in the target station. 
so here the proposed solution:
The program should take the cheapest target sell order and compare with the cheapest source sell order.

**Describe alternatives you've considered**
N/A

**Additional context**
further steps could be: if you find a profitable trade route, place a buy order above the most expensive buy order in the source station -> transport to target station -> place a sell order below the cheapest sell order in the target sation.

**Comment by awhipp** [comment]
Good find. This is a bug. The sorting on Sell Order > Sell Order is incorrect.

It was introduced in the latest code change. I am working on fixing it now.

**Comment by awhipp** [comment]
@Sukkulente This fix is currently live on dev.evetrade.space

Tested it out pretty significantly, but I will continue to test it out for the next 30min and taking it live.

So far it looks like it is working out pretty well. Made a small 10k m3 trip from Amarr to Jita and made about 135mil already on ammunition alone.

**Comment by Sukkulente** [comment]
Awesome, thank you!

Am June 4, 2019 11:44:58 PM UTC schrieb Alexander Whipp <notifications@github.com>:
@Sukkulente This fix is currently live on dev.evetrade.space

Tested it out pretty significantly, but I will continue to test it out
for the next 30min and taking it live.

So far it looks like it is working out pretty well. Made a small 10k m3
trip from Amarr to Jita and made about 135mil already on ammunition
alone.
